### PR TITLE
Feature/health check grace period

### PR DESCRIPTION
**Pull request by reiki4040**
Hi.
I added 'health check grace period' support.

'health check grace period' is added ECS at last Dec.

AWS Blog Post for about 'health check grace period'
https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-ecs-adds-elb-health-check-grace-period/?nc1=h_ls

AWS Document (page bottom 'healthCheckGracePeriodSeconds')
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html

### CODE REVIEW

**Comment by reiki4040** [comment]
hmm, I will check failed.

**Comment by reiki4040** [comment]
got error

```
Running RuboCop...
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in .rubocop.yml, please update it)
RuboCop failed!
```

I tried below and rubocop again, however rubocop failed.
```
diff --git a/.rubocop.yml b/.rubocop.yml
index 4e10837..09ffc00 100644
--- a/.rubocop.yml
+++ b/.rubocop.yml
@@ -35,7 +35,9 @@ Style/StderrPuts:
   Enabled: false
 Style/TrailingCommaInArguments:
   Enabled: false
-Style/TrailingCommaInLiteral:
+Style/TrailingCommaInArrayLiteral:
+  Enabled: false
+Style/TrailingCommaInHashLiteral:
   Enabled: false

 Performance/RedundantBlockCall:
```

local `bundle exec rake` show
```
(more logs...)

lib/hako/yaml_loader.rb:37:29: C: Naming/UncommunicativeMethodParamName: Method parameter must be longer than 3 characters.
      def revive_hash(hash, o)
                            ^

80 files inspected, 223 offenses detected

2 errors occurred:
An error occurred while Lint/UnneededCopEnableDirective cop was inspecting (local path)/hako/spec/hako/schema/structure_spec.rb.
An error occurred while Lint/UnneededCopEnableDirective cop was inspecting (local path)/hako/spec/hako/schema/table_spec.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.53.0 (using Parser 2.5.0.2, running on ruby 2.3.0 x86_64-darwin14)
RuboCop failed!
```

this cause is Mac...?(or really bug?)
I tried from error message. however, I could not resolved it.

**Comment by eagletmt** [comment]
Thanks. I've fixed rubocop errors in master https://github.com/eagletmt/hako/commit/ab42613e1f8c4d918575cd7fd6e82dfada296427

**Comment by reiki4040** [comment]
thanks!

**Pull request merged**
