### PR TITLE
Add rcredstash env_provider

### PR DESCRIPTION
**Pull request by moaikids**
I opened this pull request to add a new env_provider using `rcredstash` ( <https://github.com/adorechic/rcredstash> ). This reason is that I want to encrypt the value set for the environment variable in my situation.
Please look at it.

```
$ rcredstash put encrypted.some_password 
secret value> veryverysecret
$ rcredstash get encrypted.some_password 
veryverysecret
```

```
  env:
    $providers:
      - type: rcredstash
    SOME_PASSWORD: ‘#{encrypted.some_password}'
```

```
Environment Variables
Key	Value
SOME_PASSWORD	veryverysecret
```

### CODE REVIEW

**Comment by sorah** [comment]
Gemify like https://github.com/eagletmt/hako-etcenv ❓  Sounds there's no need to bundle in hako.gem itself.

**Comment by moaikids** [comment]
I see.I will do that.

**Comment by moaikids** [comment]
Currently, I added `hako-rcredstash` in rubygems
https://rubygems.org/gems/hako-rcredstash

**Comment by eagletmt** [comment]
👍

**Pull request closed without merging**
